### ISSUE TITLE
Various display width issues with TB 115

### ISSUE THREAD

**Issue by original-birdman** [jlx84/lightning-calendar-tabs#11]
With Lightning Calendar Tabs active *and* the Event/Tasks window open (F11)

- Narrow the window (do not have it full screen).
- Select Multiweek mode
- Click > to move forward a week. As you get to the last 2 tabs the Calendar entries widen and the right-hand ones flow underneath the Event/Tasks window.

If you switch to Day view (even with the Event/Tasks window switched off) then the display becomes wider that the screen, and the Calendar toolbar option to switch back to week/multiweek/month mode disappears off the right-hand end of the screen.

**Comment by original-birdman** [comment]
OK. I can see what is happening....

In the versions for TB before v115, the tab line was scrollable. This meant it shrank (if it could) as you narrowed the window width.
The version for TB115 (3.0) doesn't have this as scrollable, so the whole calendar pane has a minimum width of the full length of the calendar tab line.
This explains why the Day view makes the options disappear - they are actually out of view off the right-hand side of the screen, as the list of day tabs is quite wide.
Unless this tab list can be scrollable again the extension becomes virtually unusable.

**Comment by jlx84** [comment]
I think that this fixes the issue: https://github.com/jlx84/lightning-calendar-tabs/commit/1d69776e8d169b0e393a8be737c278dab796aa83

These lines:

```
this.tabs.style.minWidth = "1px";
this.tabs.style.maxWidth = "500px";
```

Although I do not understand why...

Will be in next release.

**Comment by original-birdman** [comment]
FYI:
I've just updated to 3.2 in my TB install on Windows. This seemed not to work.  Restarting TB had no effect,
**However**, disabling the extension, restarting TB and then re-enabling the extension got things going.

Doesn't seem to make much sense, but does fit in with what I saw on my (main) Linux installation.

Perhaps this might shed extra light into what is going on?
