### ISSUE TITLE
Month tabs missing TB v133

### ISSUE THREAD

**Issue by 99JoeSoap** [jlx84/lightning-calendar-tabs#13]
I am using LCT v3.2.  I have edited the manifest to allow LCT to work with versions later than TBv117.  It has all worked well up to TBv132.  Since the update to TB v133 the tabs still display in the Day, Week and Multiweek views but do not show in the Month view.

**Comment by jlx84** [comment]
Fixed in version 3.4 which was just uploaded to addons portal.
