### ISSUE TITLE
Make the addon restartless or convert to WebExtension

### ISSUE THREAD

**Issue by jlx84** [jlx84/lightning-calendar-tabs#6]
Otherwise the addon will stop working from TB 63 and newer.

Here is old FF guide, will probably be almost same for TB: https://developer.mozilla.org/en-US/docs/Archive/Add-ons/How_to_convert_an_overlay_extension_to_restartless

Some more info here: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63

**Comment by jorgk3** [comment]
It would be easier to leave it at an overlay XUL extension, see:
https://developer.thunderbird.net/add-ons/tb68/overlays
https://developer.thunderbird.net/add-ons/tb68/changes
I've made a start as per my private message.

**Comment by jlx84** [comment]
I agree, see my email reply.
